### ISSUE TITLE
Consider publishing current master as 0.1.0?

### ISSUE THREAD

**Issue by WiSaGaN** [dpc/async-readline#6]
Hello @dpc , I am wondering if we could publish the current master as 0.1.0 on crates.io.

Although this is currently only a prototype, and there are many desirable fixes and improvements we can make on current codebase to make it better suited for a public release, it would be beneficial for crates that current depends on current master:

* To remove the dependency on this particular git repository (deleting current git repo would not cause issue for exsiting user)
* To facilitate publishing crates in alternative repositories (currently it does not play nice with respect of alternative repo)

Is this possible to do, or is there any better alternatives now?

**Comment by dpc** [comment]
Hi @WiSaGaN I'm happy that you find this project useful/interesting. I suggest, just go ahead and publish it under your own ownership. Unfortunately I don't think I'll find time in the near future to do anything about it, so just go ahead if you want. If you want a different license or something, I'm all open.

**Comment by dpc** [comment]
If you want I can just reassign ownership so old links will redirect to your own username or something.

**Comment by WiSaGaN** [comment]
Thank you @dpc . In this case I just published the crate as is (added a required description) [here](https://crates.io/crates/async-readline). If you later or anyone else wants take the ownership, just let me know.

**Comment by dpc** [comment]
@WiSaGaN If you're planing to do any work on it, please fill a PR that would put a link to your own repo in the README or something.

**Comment by WiSaGaN** [comment]
@dpc , I don't have plans for any further work right now.
